# Generated by Django 2.2 on 2019-06-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
